apiVersion: v1
kind: Pod
metadata:
  name: webgoat
  namespace: jenkins
  labels:
    run: webgoat
spec:
  imagePullSecrets: 
  - name: regcred
  containers:
  - name: webgoat
    image: cgi-webgoat:4
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat
  namespace: jenkins
  labels:
    run: webgoat
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: webgoat
